### PR TITLE
fix: Change evaluateJSONataExpression  to use callback

### LINKED ISSUE #898: Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback
### Describe the bug

Just upgraded to node red 3.1.0-beta.2 but greeted with the following
```
[warn] Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. 
This will not be optional in Node-RED 4.0. Please identify the node from the following stack 
and check for an update on npm. If none is available, please notify the node author.
[warn] Error
at Object.evaluateJSONataExpression (/home/pi/.node-red/node_modules/@node-red/util/lib/util.js:777:18)
at JSONataService.evaluate (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)
at TypedInputService.getValue (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/TypedInputService.js:58:85)
at EventsAll.getTypedInputValue (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:134:39)
at /home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:138:32
at Array.forEach (<anonymous>)
at EventsAll.setCustomOutputs (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:137:20)
at EventsAll.onHaEventsAll (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/events-all/controller.js:57:18)
at EventEmitter.<anonymous> (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/EventsNode.js:39:17)
at EventEmitter.emit (node:events:525:35)
at Websocket._Websocket_emitEvent (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/homeAssistant/Websocket.js:394:67)
at Websocket.onClientEvents (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/homeAssistant/Websocket.js:238:87)
at Object.callback (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/homeAssistant/Websocket.js:143:65)
at /home/pi/.node-red/node_modules/home-assistant-js-websocket/dist/haws.cjs:236:34
at Array.forEach (<anonymous>)
at Connection._handleMessage (/home/pi/.node-red/node_modules/home-assistant-js-websocket/dist/haws.cjs:231:26)
at callListener (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/event-target.js:290:14)
at WebSocket.onMessage (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/event-target.js:209:9)
at WebSocket.emit (node:events:513:28)
at Receiver.receiverOnMessage (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/websocket.js:1184:20)
at Receiver.emit (node:events:513:28)
at Receiver.dataMessage (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/receiver.js:541:14)

```

### To Reproduce

upgraded node-red by ` npm install node-red@next`

### Expected behavior

_No response_

### Screenshots

_No response_

### Example Flow

_No response_

### This package's version (not the Home Assistant add-on version)

0.49

### Is Node-RED running in Docker?

No

### Node-RED version

3.1.0-beta.2

### Node.js version

18.15.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zachowj**
This fixes the deprecated warning for evaluateJSONataExpression

Fixes #898

### CODE REVIEW

**Comment by werkstrom** [comment]
Awesome @zachowj Thank you for so much for this

**Comment by oidsaasd** [comment]
Great!

Can someone guide me on how to get this branch installed into Node-Red? The Node-RED Manage Palette only views main branch.

**Comment by mraita** [comment]
just updated node-red addon to 14.5.0 v3.1; Problem not solved !!!

**Comment by MStcz** [comment]
> just updated node-red addon to 14.5.0 v3.1; Problem not solved !!!
> 
> edit: the fix #898 works

Hi, I think it is related to "node-red-contrib-home-assistant-websocket". As I see, the new version is not out yet. We are waiting for newer than v0.56.1.

**Comment by TomK** [comment]
you can install the pre-release by following instructions in the [release](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/releases/tag/v0.57.0-beta.1)

**Comment by edd189** [comment]
How much longer is this going to take to get pushed into the official version? It has been three months. These errors are still filling up my log. Not interested in having to manually add beta versions.

**Comment by zachowj** [comment]
@edd189 This was included in the 0.57.0 version release on Oct 2, 2023.

[v0.57.0](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/releases/tag/v0.57.0)

**Pull request merged**
